name: Update test.html with current time

on:
  push: # 코드가 푸시될 때마다 작업을 실행
    branches: [ main ] # main 브랜치에서만 실행

jobs:
  build:
    runs-on: ubuntu-latest # 실행할 환경 선택
    steps:
    - uses: actions/checkout@v2 # 리포지토리 체크아웃
    - name: Use Node.js # 노드 설정
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Set up Python # 파이썬 설정
      uses: actions/setup-python@v2
      with:
        python-version: 3.x # 파이썬 버전 선택
    - name: Install dependencies # 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python script # 파이썬 코드 실행
      run: |
        python main.py
    - name: Commit updated index.html # 변경된 index.html 파일 커밋
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Your Name # 사용자 이름
        author_email: your_email@example.com # 사용자 이메일
        message: Update index.html with current time # 커밋 메시지
        add: "index.html" # 변경된 파일 추가
